---
name:             DustBin
main:             presentkim\dustbin\DustBinMain
version:          1.0.1
api:              [3.0.0, 3.0.0-ALPHA10]
author:           PresentKim

permissions:
  dustbin.cmd:
    description:  DustBin main command
    default:      true
...
